---
- name: Check 'openssl_certificates_directory' parameter
  assert:
    that:
      - "openssl_certificates_directory is defined"
      - "openssl_certificates_directory | length > 0"
    fail_msg: "parameter 'openssl_certificates_directory' is missing"

- name: Check 'openssl_working_directory' parameter
  assert:
    that:
      - "openssl_working_directory is defined"
      - "openssl_working_directory | length > 0"
    fail_msg: "parameter 'openssl_working_directory' is missing"
