---
- name: create volume directory
  file:
    path: "{{working_directory}}"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create csr directory
  file:
    path: "{{working_directory}}/csr"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create ca directory
  file:
    path: "{{working_directory}}/ca"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create certs directory
  file:
    path: "{{certificates_directory}}"
    state: directory
    owner: root
    group: root
    mode: 755
