---
- name: check 'item' parameter
  assert:
    that:
      - "item != ''"
    fail_msg: "parameter 'item' incorrect or missing"

- name: Setup variables for Cert
  set_fact:
    ca_private_key_path: "{{volume}}/private/{{ca_name}}.pem"
    ca_cert_path: "{{volume}}/crt/{{ca_name}}.crt"
    cert_private_key_path: "{{volume}}/private/{{item}}.pem"
    cert_csr_path: "{{volume}}/csr/{{item}}.csr.pem"
    cert_path: "{{volume}}/crt/{{item}}.crt"

- name: Generate an OpenSSL RSA private key
  openssl_privatekey:
    path: "{{cert_private_key_path}}"
    size: 4096

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{cert_csr_path}}"
    privatekey_path: "{{cert_private_key_path}}"
    common_name: "{{item}}"

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "{{cert_path}}"
    csr_path: "{{cert_csr_path}}"
    ownca_path: "{{ca_cert_path}}"
    ownca_privatekey_path: "{{ca_private_key_path}}"
    provider: ownca
