---
- name: Setup variables for CA
  set_fact:
    ca_private_key_path:
      "{{ openssl_working_directory }}/ca/{{ openssl_ca_name }}.pem"
    ca_csr_path:
      "{{ openssl_working_directory }}/csr/{{ openssl_ca_name }}.csr.pem"
    ca_cert_path: "{{ openssl_working_directory }}/ca/{{ openssl_ca_name }}.crt"

- name: Generate an OpenSSL RSA private key
  openssl_privatekey:
    path: "{{ ca_private_key_path }}"
    size: "{{ openssl_ca_key_size }}"

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_private_key_path }}"
    common_name: "{{ openssl_ca_name }}"

- name: Check if certificate file exists
  stat:
    path: "{{ ca_cert_path }}"
  register: cert_file_result

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ca_cert_path }}"
    privatekey_path: "{{ ca_private_key_path }}"
    csr_path: "{{ ca_csr_path }}"
    provider: selfsigned
  when: not cert_file_result.stat.exists

- name: download CA certificate
  fetch:
    src: "{{ ca_cert_path }}"
    dest: "{{ openssl_download_dir }}/{{ openssl_ca_name }}.pem"
    flat: true
  changed_when: false
