---
- name: create volume directory
  file:
    path: "{{volume}}"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create csr directory
  file:
    path: "{{volume}}/csr"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create ca directory
  file:
    path: "{{volume}}/ca"
    state: directory
    owner: root
    group: root
    mode: 775

- name: create certs directory
  file:
    path: "{{volume}}/certs"
    state: directory
    owner: root
    group: root
    mode: 755
