---
- name: check 'item' parameter
  assert:
    that:
      - item is defined
      - item | length > 0
    fail_msg: "parameter 'item' incorrect or missing"

- name: Setup variables for Cert
  set_fact:
    ca_private_key_path:
      "{{ openssl_working_directory }}/ca/{{ openssl_ca_name }}.pem"
    ca_cert_path: "{{ openssl_working_directory }}/ca/{{ openssl_ca_name }}.crt"
    cert_csr_path: "{{ openssl_working_directory }}/csr/{{ item }}.csr.pem"
    cert_directory: "{{ openssl_certificates_directory }}/{{ item }}"
    cert_private_key_path:
      "{{ openssl_certificates_directory }}/{{ item }}/privkey.pem"
    cert_path: "{{ openssl_certificates_directory }}/{{ item }}/fullchain.pem"
    trust_cert_path: "{{ openssl_certificates_directory }}/{{ item }}/chain.pem"

- name: create certificate directory
  file:
    path: "{{ cert_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Generate an OpenSSL RSA private key
  openssl_privatekey:
    path: "{{ cert_private_key_path }}"
    size: "{{ openssl_cert_key_size }}"

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ cert_csr_path }}"
    privatekey_path: "{{ cert_private_key_path }}"
    common_name: "{{ item }}"

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "{{ cert_path }}"
    csr_path: "{{ cert_csr_path }}"
    ownca_path: "{{ ca_cert_path }}"
    ownca_privatekey_path: "{{ ca_private_key_path }}"
    provider: ownca

- name: Create the hard link to CA
  file:
    src: "{{ ca_cert_path }}"
    dest: "{{ trust_cert_path }}"
    state: hard
