---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: vagrant-openssl-noble
    box: cloud-image/ubuntu-24.04
  - name: vagrant-openssl-jammy
    box: cloud-image/ubuntu-22.04
  - name: vagrant-openssl-focal
    box: cloud-image/ubuntu-20.04
  - name: vagrant-openssl-bookworm
    box: cloud-image/debian-12
    groups:
      - debian
  - name: vagrant-openssl-bullseye
    box: cloud-image/debian-11
    groups:
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      vagrant-openssl-noble:
        ca_dir: vagrant-openssl-noble
      vagrant-openssl-jammy:
        ca_dir: vagrant-openssl-jammy
      vagrant-openssl-focal:
        ca_dir: vagrant-openssl-focal
      vagrant-openssl-bookworm:
        ca_dir: vagrant-openssl-bookworm
      vagrant-openssl-bullseye:
        ca_dir: vagrant-openssl-bullseye

verifier:
  name: ansible
