---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-openssl-noble
    image: docker.io/borisskert/python3:noble
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openssl-jammy
    image: docker.io/borisskert/python3:jammy
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
  - name: ansible-openssl-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker

  - name: ansible-openssl-bookworm
    image: docker.io/borisskert/python3:bookworm
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian
  - name: ansible-openssl-bullseye
    image: docker.io/borisskert/python3:bullseye
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
      - debian

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-openssl-noble:
        ca_dir: docker-openssl-noble
      ansible-openssl-jammy:
        ca_dir: docker-openssl-jammy
      ansible-openssl-focal:
        ca_dir: docker-openssl-focal
      ansible-openssl-bookworm:
        ca_dir: docker-openssl-bookworm
      ansible-openssl-bullseye:
        ca_dir: docker-openssl-bullseye

verifier:
  name: ansible
