---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-openssl-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      ansible-openssl-stretch:
        ca_dir: docker-openssl-stretch
      ansible-openssl-buster:
        ca_dir: docker-openssl-buster
      ansible-openssl-focal:
        ca_dir: docker-openssl-focal
      ansible-openssl-bionic:
        ca_dir: docker-openssl-bionic
      ansible-openssl-xenial:
        ca_dir: docker-openssl-xenial

verifier:
  name: ansible
