---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-openssl-self-signed-certs
      download_dir: ".tmp/{{ ca_dir }}"
      sites:
        - my.first.site
        - my.second.site
        - my.third.site
